### ISSUE TITLE
night theme

### ISSUE THREAD

**Issue by Matheus1300** [joonkyu/ericdoa#1]
hello, i was using the night theme you made for powercord for a long time, but apparently you have deleted the repo. I have reseted my pc and i lose the CSS code, you cand send it for me, please? it's my favorite theme

**Comment by joonkyu** [comment]
Yo! Thank you for the appreciation, just made the repository public again! :)

**Comment by Matheus1300** [comment]
thank you so much <3

**Comment by Matheus1300** [comment]
thank you so much <3
